### ISSUE TITLE
Mega Links

### ISSUE THREAD

**Issue by AbdulRehmanJanjua-InfoSec** [acaceres2176/scylla#1]
All the Mega links seem to be broken. Please fix these links.

**Comment by hyp3ri0n-ng** [comment]
I removed the raw DB download due to bandwidth costs, data is available (for free ofc) if you email acaceres@0-sec.net

**Comment by hyp3ri0n-ng** [comment]
Please note I'm getting lots of queries about this. I'm collecting all the data in one place, it just takes forever due to the sheer amount. It'll take about a day just to compress.... A link will be up soon though for those that have asked for it.
