### ISSUE TITLE
Mega links expired

### ISSUE THREAD

**Issue by OneWayHandshake** [acaceres2176/scylla#2]
Mega links have expired as of ~ 12 hours ago.

Would really appreciate if we could fix this, as I spent the money on a mega pro plan for a month to get these downed reliably.

**Comment by hyp3ri0n-ng** [comment]
hey there, shoot me a message at scylla@ipriva.info if you still want to get this resolved!

**Comment by hyp3ri0n-ng** [comment]
I removed all links to databases, they are still available if you shoot me an email acaceres@0-sec.net
