### ISSUE TITLE
search is doing wildcards when it shouldn't

### ISSUE THREAD

**Issue by digininja** [acaceres2176/scylla#4]
This search, I assume, should only return results with the email address "robin[@]digininja.org" but instead returns anything with "robin" in the email field.

<https://scylla.sh/search?q=Email%3Arobin@digininja.org>

**Comment by Rival420** [comment]
noticed that too, when I try to find an Email I have noticed that not specifying @whatever is more reliable than giving in the whole email.

**Comment by hyp3ri0n-ng** [comment]
i've noticed the same thing too. AFAICT it looks like it's tokenizing at @. I'll look into the solr/lucene docs and see if i can prevent it from doing that!

**Comment by hyp3ri0n-ng** [comment]
I was fiddling with the queries and what users liked best. I landed on: Lucene query syntax, default tokenizers. You shouldn't see this issue anymore.
