### ISSUE TITLE
Domain search default wildcards

### ISSUE THREAD

**Issue by Rival420** [acaceres2176/scylla#5]
Hi this is more of a request but would it be possible to add a default wildcard behind the query for domain?
when I query for Domain:dropbox it returns nothing:

https://scylla.sh/search?q=Domain%3Adropbox 

I have to query for Domain:dropbox* or Domain:dropbox.com. Domain:dropbox.com* is also working so that could be an improvement

**Comment by hyp3ri0n-ng** [comment]
I used to do this but removed it because people were complaining of too many results :-/. If you want to match anything with dropbox.com for example, try *dropbox.com*
