### ISSUE TITLE
want to donate with crypto

### ISSUE THREAD

**Issue by jujijoog** [acaceres2176/scylla#8]
hi i want to donate with crypto, dont have paypal.
i would also like to contribute data. i have quite a lot.
aaaand also as someone mentioned i believe it seems to be doing wildcard when it shouldnt unless im just not understanding lucene right. 
if you wouldnt mind contact me on telegram @bashscripts
im happy to make a solid donation, really appreciate this project.

**Comment by acaceres2176** [comment]
hey there, apologies I know this is quite old, for some reason I haven't been receiving issue notifications. Much appreciated on the crypto! I will definitely put up an address so folks can donate with btc or xmr!
