### ISSUE TITLE
Problem with GET method with API

### ISSUE THREAD

**Issue by TempsAdditionnel** [acaceres2176/scylla#9]
Hey bro, thanks for your work !
Your API don't work.. Nothing was returned.
I try to get response from CURL with "Accept: application/json" in Header but he don't work.
Can you fix this?

**Comment by hyp3ri0n-ng** [comment]
hmm, could you shoot me the exact command and output you're seeing please?

**Comment by Shadow0ps** [comment]
Seems to work ok.  Tested Example below.
`
curl "https://scylla.sh/search?q=Email:someonestolemycookies%40example.com&num=1000&from=0" \
     -H 'Accept: application/json' \
     -u 'username:password'`
